Projenin Amacı
Bu projenin temel amacı, bir işletmenin 1 haftalık süreçte 5 farklı ürün grubundan elde ettiği satış verilerini simüle etmek ve bu veriler üzerinde temel veri analitiği operasyonlarını gerçekleştirmektir. Ham sayısal verileri anlamlı içgörülere (en verimli gün, toplam ciro, ürün performansı vb.) dönüştürme sürecini kapsar.

 NumPy Neden Kullanılır?
Veri analizinde NumPy'ın tercih edilmesinin kritik nedenleri şunlardır:

Hız ve Performans: Vektörize işlemler sayesinde standart Python listelerinden kat kat daha hızlıdır.

Bellek Yönetimi: Verileri bellekte bitişik bloklar halinde tutarak optimize edilmiş bir depolama sunar.

Çok Boyutlu Yapı: Matrisler (satır ve sütunlar) üzerinde matematiksel işlemleri kolaylaştırır.

Ekosistem Uyumu: Pandas, Matplotlib ve Scikit-learn gibi kütüphanelerin temelini oluşturur.

 Kullanılan NumPy Konuları
Proje boyunca aşağıdaki teknik yetkinlikler uygulanmaktadır:

Dizi Oluşturma: np.random.randint ile simülasyon verisi üretimi.

Dizi Nitelikleri: shape, ndim, dtype ve size incelemesi.

İndeksleme & Dilimleme (Indexing & Slicing): Veri setinden belirli alt kümelere erişim.

Agregasyon Metodları: sum, mean, max, min gibi istatistiksel fonksiyonlar.

Eksen (Axis) Yönetimi: Satır (axis=1) ve sütun (axis=0) bazlı operasyonlar.

Şekillendirme (Reshaping): reshape, transpose ve flatten ile veri formatı değişikliği.

In [27]:
import numpy as np
satislar=np.random.randint(0,100, size=(7,5)) #7gün 5 satış kategorisi olacak şekilde rastgele satış verileri atanır.
print("7 Günlük Satış Verileri:")
satislar

7 Günlük Satış Verileri:


array([[18,  5, 94, 31, 77],
       [68, 58, 73, 16, 16],
       [93, 27, 68,  3, 51],
       [30, 22, 52,  3, 59],
       [99, 54, 44, 95, 85],
       [58, 44, 29, 27, 31],
       [75,  6, 96, 95, 13]], dtype=int32)

In [29]:
#array özellikleri
(f"Dizi Boyutu(shape): {satislar.shape}")
(f"Boyut Sayısı(ndim): {satislar.ndim}")
(f"Veri Tipi(dtype):  {satislar.dtype}")
(f"Toplam Eleman Sayısı(size): {satislar.size}")

'Toplam Eleman Sayısı(size): 35'

In [35]:
birinciGunSatislar =satislar[0,:]
print(f"Birinci Günün Satışaları:")
print(birinciGunSatislar)
ilkUrunHaftalik= satislar[:,0]
print(f"Birinci Ürünün Haftalık Satışı:")
print(ilkUrunHaftalik)
ilkUcGun= satislar[0:3, :]
print(f"İlk Üç Gün Satışları:")
print(ilkUcGun)

Birinci Günün Satışaları:
[18  5 94 31 77]
Birinci Ürünün Haftalık Satışı:
[18 68 93 30 99 58 75]
İlk Üç Gün Satışları:
[[18  5 94 31 77]
 [68 58 73 16 16]
 [93 27 68  3 51]]


In [55]:
toplamSatis= satislar.sum()
print(f"Haftalık Toplam Satış: {toplamSatis}")
gunlukOrtSatis= toplamSatis/7
print(f"Günlük Ortalama Satış: {gunlukOrtSatis}")
enYuksekSatis= satislar.max()
print(f"En Yüksek Satış: {enYuksekSatis}")
enDusukSatis= satislar.min()
print(f"En Düşük Satış: {enDusukSatis}")

Haftalık Toplam Satış: 1715
Günlük Ortalama Satış: 245.0
En Yüksek Satış: 99
En Düşük Satış: 3


In [61]:
gunlukToplamSatis=satislar.sum(axis=1)
print(f"Günlük Toplam Satış: {gunlukToplamSatis}")
# Gün bazlı toplam satış (Her satırın kendi toplamı)
# axis=1: Satır boyunca (soldan sağa) işlem yapar. 
# 7 günün her biri için 5 ürünün toplamını verir. Sonuç: 7 elemanlı bir dizi.
urunToplamSatis=satislar.sum(axis=0)
print(f"Ürün Satışları Toplamı:  {urunToplamSatis}")
# 2. Ürün bazlı toplam satış (Her sütunun kendi toplamı)
# axis=0: Sütun boyunca (yukarıdan aşağıya) işlem yapar.
# 5 ürünün her biri için 7 günlük toplamı verir. Sonuç: 5 elemanlı bir dizi.

# NumPy'da 'axis' parametresi, işlemin hangi yöne doğru daraltılacağını belirler
#- axis=0 (Sütunlar): İşlem yukarıdan aşağıya doğru yapılır. 
# Satırları ezer ve her sütun için tek bir sonuç üretir.
# axis=1 (Satırlar): İşlem soldan sağa doğru yapılır. 
# Sütunları ezer ve her satır için tek bir sonuç üretir.

Günlük Toplam Satış: [225 231 242 166 377 189 285]
Ürün Satışları Toplamı:  [441 216 456 270 332]


In [79]:
satislarReshape= satislar.reshape(5,7)
print(f"Reshape (5x7) Hali: \n {satislarReshape}")
satislarTranspose= satislar.transpose()
print(f"Transpose Hali:\n {satislarTranspose}")
# Flatten veya Ravel: Çok boyutlu diziyi tek boyuta (vektör) indirger
# Tüm haftalık veriyi tek bir liste gibi arka arkaya dizer.
satislarFlat= satislar.flatten()
print(f"Flatten Hali:\n  {satislarFlat}")

Reshape (5x7) Hali: 
 [[18  5 94 31 77 68 58]
 [73 16 16 93 27 68  3]
 [51 30 22 52  3 59 99]
 [54 44 95 85 58 44 29]
 [27 31 75  6 96 95 13]]
Transpose Hali:
 [[18 68 93 30 99 58 75]
 [ 5 58 27 22 54 44  6]
 [94 73 68 52 44 29 96]
 [31 16  3  3 95 27 95]
 [77 16 51 59 85 31 13]]
Flatten Hali:
  [18  5 94 31 77 68 58 73 16 16 93 27 68  3 51 30 22 52  3 59 99 54 44 95
 85 58 44 29 27 31 75  6 96 95 13]
